# Generated by Django 4.2.17 on 2024-12-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
