# Generated by Django 4.2.17 on 2024-12-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
