# Generated by Django 4.2.17 on 2024-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
