# Generated by Django 4.2.17 on 2024-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
