# Generated by Django 4.2.17 on 2024-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
