# Generated by Django 4.2.17 on 2024-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_alter_apply_link_alter_news_image_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='links_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
