# Generated by Django 4.2.17 on 2024-12-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0027_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
